"""initial schema

Revision ID: 68a46bfef61c
Revises: 
Create Date: 2026-06-29 19:22:16.501619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68a46bfef61c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_weekend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'round', name='uq_weekend_year_round')
    )
    op.create_index(op.f('ix_race_weekend_round'), 'race_weekend', ['round'], unique=False)
    op.create_index(op.f('ix_race_weekend_year'), 'race_weekend', ['year'], unique=False)
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followed_constructor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_email'), 'subscriber', ['email'], unique=True)
    op.create_table('candidate_insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('robustness_score', sa.Float(), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['weekend_id'], ['race_weekend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_insight_signal_type'), 'candidate_insight', ['signal_type'], unique=False)
    op.create_index(op.f('ix_candidate_insight_weekend_id'), 'candidate_insight', ['weekend_id'], unique=False)
    op.create_table('constructor_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_id', sa.Integer(), nullable=False),
    sa.Column('constructor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('high_score', sa.Float(), nullable=True),
    sa.Column('mid_score', sa.Float(), nullable=True),
    sa.Column('low_score', sa.Float(), nullable=True),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('lap_deficit_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['weekend_id'], ['race_weekend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructor_index_constructor'), 'constructor_index', ['constructor'], unique=False)
    op.create_index(op.f('ix_constructor_index_weekend_id'), 'constructor_index', ['weekend_id'], unique=False)
    op.create_table('insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('header', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_web', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_tool_calls_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['weekend_id'], ['race_weekend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_weekend_id'), 'insight', ['weekend_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['weekend_id'], ['race_weekend.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekend_id', 'session_type', name='uq_session_weekend_type')
    )
    op.create_index(op.f('ix_session_weekend_id'), 'session', ['weekend_id'], unique=False)
    op.create_table('attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('corner_number', sa.Integer(), nullable=False),
    sa.Column('speed_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constructor_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constructor_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delta_s', sa.Float(), nullable=True),
    sa.Column('car_pct', sa.Float(), nullable=True),
    sa.Column('driver_pct', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_corner_number'), 'attribution', ['corner_number'], unique=False)
    op.create_index(op.f('ix_attribution_session_id'), 'attribution', ['session_id'], unique=False)
    op.create_table('fingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corner_number', sa.Integer(), nullable=False),
    sa.Column('brake_point', sa.Float(), nullable=True),
    sa.Column('trail_brake_dur', sa.Float(), nullable=True),
    sa.Column('min_speed', sa.Float(), nullable=True),
    sa.Column('throttle_point', sa.Float(), nullable=True),
    sa.Column('throttle_ramp', sa.Float(), nullable=True),
    sa.Column('steer_at_apex', sa.Float(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('clean_lap_count', sa.Integer(), nullable=False),
    sa.Column('compound', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fingerprint_corner_number'), 'fingerprint', ['corner_number'], unique=False)
    op.create_index(op.f('ix_fingerprint_driver'), 'fingerprint', ['driver'], unique=False)
    op.create_index(op.f('ix_fingerprint_session_id'), 'fingerprint', ['session_id'], unique=False)
    op.create_table('session_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('driver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constructor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gap_to_leader', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_result_session_id'), 'session_result', ['session_id'], unique=False)
    op.create_table('stint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lap_start', sa.Integer(), nullable=True),
    sa.Column('lap_end', sa.Integer(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('lap_times_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stint_driver'), 'stint', ['driver'], unique=False)
    op.create_index(op.f('ix_stint_session_id'), 'stint', ['session_id'], unique=False)
    op.create_table('straight_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drs_zone_id', sa.Integer(), nullable=False),
    sa.Column('max_speed_kmh', sa.Float(), nullable=True),
    sa.Column('trap_speed_kmh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_straight_segment_driver'), 'straight_segment', ['driver'], unique=False)
    op.create_index(op.f('ix_straight_segment_drs_zone_id'), 'straight_segment', ['drs_zone_id'], unique=False)
    op.create_index(op.f('ix_straight_segment_session_id'), 'straight_segment', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_straight_segment_session_id'), table_name='straight_segment')
    op.drop_index(op.f('ix_straight_segment_drs_zone_id'), table_name='straight_segment')
    op.drop_index(op.f('ix_straight_segment_driver'), table_name='straight_segment')
    op.drop_table('straight_segment')
    op.drop_index(op.f('ix_stint_session_id'), table_name='stint')
    op.drop_index(op.f('ix_stint_driver'), table_name='stint')
    op.drop_table('stint')
    op.drop_index(op.f('ix_session_result_session_id'), table_name='session_result')
    op.drop_table('session_result')
    op.drop_index(op.f('ix_fingerprint_session_id'), table_name='fingerprint')
    op.drop_index(op.f('ix_fingerprint_driver'), table_name='fingerprint')
    op.drop_index(op.f('ix_fingerprint_corner_number'), table_name='fingerprint')
    op.drop_table('fingerprint')
    op.drop_index(op.f('ix_attribution_session_id'), table_name='attribution')
    op.drop_index(op.f('ix_attribution_corner_number'), table_name='attribution')
    op.drop_table('attribution')
    op.drop_index(op.f('ix_session_weekend_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_insight_weekend_id'), table_name='insight')
    op.drop_table('insight')
    op.drop_index(op.f('ix_constructor_index_weekend_id'), table_name='constructor_index')
    op.drop_index(op.f('ix_constructor_index_constructor'), table_name='constructor_index')
    op.drop_table('constructor_index')
    op.drop_index(op.f('ix_candidate_insight_weekend_id'), table_name='candidate_insight')
    op.drop_index(op.f('ix_candidate_insight_signal_type'), table_name='candidate_insight')
    op.drop_table('candidate_insight')
    op.drop_index(op.f('ix_subscriber_email'), table_name='subscriber')
    op.drop_table('subscriber')
    op.drop_index(op.f('ix_race_weekend_year'), table_name='race_weekend')
    op.drop_index(op.f('ix_race_weekend_round'), table_name='race_weekend')
    op.drop_table('race_weekend')
    # ### end Alembic commands ###
